### ISSUE TITLE
Question on writability of the relation

### ISSUE THREAD

**Issue by stickgrinder** [staudenmeir/laravel-merged-relations#1]
Hi @staudenmeir.
I stumbled onto your package and I have to say it's really great work.

Even if it's not documented I tried a `$model->all_related->save($relatedModelInstance)` but it doesn't work.
I guess this is not supported yet but it may be my fault... any clue?

Thanks for taking the time.

**Comment by staudenmeir** [comment]
This is not supported at the moment. What do your original relationships and the merged relationship and look like?
