### ISSUE TITLE
Adding pivot columns to the generated views

### ISSUE THREAD

**Issue by alhaji-aki** [staudenmeir/laravel-merged-relations#10]
Is it possible to add pivot columns to the generated view?

I have a `users` table and a pivot table for friends which contains the `user_id`, `friend_id` and `accepted_at`. 

Is it possible to get the `accepted_at` in the generated view?

**Comment by staudenmeir** [comment]
Not at the moment, but it's on my TODO list.

**Comment by staudenmeir** [comment]
How are you generating the view and how are the original and the merged relationships defined?

**Comment by alhaji-aki** [comment]
Below is a snippet of how the view generated.

```php
Schema::createMergeView(
    'friends_view',
    [(new User())->acceptedFriends(), (new User())->friendsAcceptedBack()]
);
```

On the users table I have an `acceptedFriends` which is for the users the current authenticated user has accepted their friend request and `friendsAcceptedBack` for the people who accepted the current authenticated user's friend request.

Then the relationships

```php
class User extends Authenticatable
{
    ...
    
    public function acceptedFriends(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'friends', 'user_id', 'friend_id')
            ->withPivot(['accepted_at'])
            ->wherePivotNotNull('accepted_at');
    }

    public function friendsAcceptedBack(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'friends', 'friend_id', 'user_id')
            ->withPivot(['accepted_at'])
            ->wherePivotNotNull('accepted_at');
    }

    public function friends(): MergedRelation
    {
        return $this->mergedRelationWithModel(User::class, 'friends_view');
    }

    ...
}
```

**Comment by alhaji-aki** [comment]
Update: I changed the view generating code to look like this and it now adds the the pivot column to the generated view

```php
Schema::createMergeView('friends_view', [
    (new User())->acceptedFriends()->select('friends.accepted_at as accepted_at'), 
    (new User())->friendsAcceptedBack()->select('friends.accepted_at as accepted_at')
]);
```

**Comment by staudenmeir** [comment]
I've released a new version for Laravel 10 that adds support for pivot tables:
https://github.com/staudenmeir/laravel-merged-relations?tab=readme-ov-file#pivot-table-data

You only need recreate your merge view.

**Comment by alhaji-aki** [comment]
Thank you! I will check it out
