### ISSUE TITLE
Seeding MergedRelationship with Model Factory

### ISSUE THREAD

**Issue by felixele217** [staudenmeir/laravel-merged-relations#11]
The User Model has a merged relationship called connections: 
```
  public function connections(): MergedRelation
  {
      return $this->mergedRelationWithModel(User::class, 'connections_view');
  }
```

which is connected with the following connections_view: 
```
  public function up()
  {
      Schema::createMergeView(
          'connections_view',
          [(new User())->acceptedConnectionsFrom(), (new User())->acceptedConnectionsTo()]
      );
  }
``` 

It merges together the connections between two users, where a user can either be the sender or the receiver of a connection request. That is why we need two relationships for it. If you do not understand what I mean, check out https://blog.codecourse.com/setting-up-laravel-friendship-relations

In my seeder or in my tests I would now like to create records for the mergedRelation like so:
```
  public function test_try_to_seed_user_with_friends() 
  {
      $user = User::factory()
                  ->hasConnections(10)
                  ->create();
  }
```

Unfortunately this throws the following error: 
```
  SQLSTATE[HY000]: General error: 1 table users has no column named laravel_foreign_key (SQL: insert into "users" ("name", "email", "email_verified_at", "password", "remember_token", "userable_id", "userable_type", "laravel_foreign_key", "updated_at", "created_at") values (Kareem Jast I, devon03@example.org, 2022-11-04 14:22:07, $2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi, CqbC0RCmTK, 2, App\Models\Site, 1, 2022-11-04 14:22:07, 2022-11-04 14:22:07))
```

Is it possible to fix it?

**Comment by staudenmeir** [comment]
Hi @felixele217,
You need to seed records for the original relationships `acceptedConnectionsFrom` and `acceptedConnectionsTo`. It's not possible to seed records for the merged relationship `connections` because it's read-only.
