### ISSUE TITLE
Sorting mergedRelation before pagination

### ISSUE THREAD

**Issue by felixele217** [staudenmeir/laravel-merged-relations#12]
Is it possible to sort a mergedRelation before pagination. The attribute 'accepted_at' I want to sort by, is an accessor which is used by the user class.
![image](https://user-images.githubusercontent.com/50794814/200822639-e88b3a75-79b0-4775-b1e9-8068d0ab11cb.png)

**Comment by staudenmeir** [comment]
Hi @felixele217,
I'm still working on proper support for pivot columns. In the meantime, you can use the workaround from #10:

```php
Schema::createMergeView(
    'connections_view',
    [
        (new User())->acceptedConnectionsFrom()->select('accepted_at'),
        (new User())->acceptedConnectionsTo()->select('accepted_at'),
    ]
);

return $currentUser->connections()->orderBy('accepted_at')->paginate(...);
```

**Comment by felixele217** [comment]
Alright. Thanks. And would it be possible to orderBy/sortBy an appended attribute from the User-Model?

**Comment by staudenmeir** [comment]
> an appended attribute from the User-Model

This kind of appended attribute? https://laravel.com/docs/9.x/eloquent-serialization#appending-values-to-json
