### ISSUE TITLE
"Invalid authorization specification" on restored DB

### ISSUE THREAD

**Issue by kebelig** [staudenmeir/laravel-merged-relations#15]
After dropping my dev database and restoring the live database containing a view created by this plugin, i get the following error:

SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'db'@'%' (using password: YES)

The other tables working like normal.
If I delete the view and re-run the migration it works again.

Is this a known problem?

**Comment by staudenmeir** [comment]
Hi @kebelig,
No, I haven't heard of any cases like yours.

> After dropping my dev database and restoring the live database containing a view created by this plugin, i get the following error:

How are you restoring the database? When are you getting this error? When you access the view?

**Comment by kebelig** [comment]
Hi @staudenmeir ,

i finally found the problem:
i take my backups with "laravel backup" by spatie. On restoring the backup-sql-file i get the following error:

```
[42000][1227] Access denied; you need (at least one of) the SUPER privilege(s) for this operation
```

And this is because of in the sql file there is a DEFINER tight before the view is created:

```
/*!50013 DEFINER=`laravel`@`localhost` SQL SECURITY DEFINER */
``` 
Now i simply remove the definer with sed with the following command (on MacOS) and can restore the database without problems 

```
sed -i backup.sql 's/\DEFINER\=`[^`]*`@`[^`]*`//g' backup.sql
```

**Comment by m-popa** [comment]
Hello and thanks for the awesome package.

The error still exists if you try to manually dump from production or with a db sync package, if I delete and rerun the migration it would work but it's a bit of hassle to do that all the time, maybe remove that definder?

Thanks,
Mihai
