### ISSUE TITLE
Failed to create merge view

### ISSUE THREAD

**Issue by androidhands** [staudenmeir/laravel-merged-relations#16]
I have error Error: Call to undefined method Staudenmeir\LaravelMergedRelations\Facades\Schema::createMergeView() in file /public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 353.

**Comment by staudenmeir** [comment]
Please share your `composer.json` file and the whole migration where this error is happening.

**Comment by androidhands** [comment]
`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": [
        "laravel",
        "framework"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "korridor/laravel-has-many-merged": "^1.0",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "staudenmeir/laravel-merged-relations": "^1.0",
        "twilio/sdk": "^7.5",
        "tymon/jwt-auth": "^2.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}`

**Comment by androidhands** [comment]
`<?php

use App\Models\Users;
use Illuminate\Database\Migrations\Migration;

use Staudenmeir\LaravelMergedRelations\Facades\Schema;


return new class extends Migration
{




    /**
     * Run the migrations.
     */
    public function up(): void
    {



        Schema::createMergeView(
            'users_merge_view',
            [(new Users())->acceptedMembersFrom(), (new Users())->acceptedMembersTo()]
        );
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropView('members_merge_view');
    }
};
`

**Comment by staudenmeir** [comment]
What output does `composer dump` give you?
