### ISSUE TITLE
Error: getColumns() must be public.

### ISSUE THREAD

**Issue by gdsrmygdsrjr** [staudenmeir/laravel-merged-relations#18]
![image](https://github.com/staudenmeir/laravel-merged-relations/assets/10488154/251e850d-ca10-4b44-8bda-ae4be0fad1d5)
![image](https://github.com/staudenmeir/laravel-merged-relations/assets/10488154/7dd6243c-5430-4bd3-a451-5d31b99837b3)

**Comment by staudenmeir** [comment]
Hi @gdsrmygdsrjr,
Thanks for reporting this. The issue was that Laravel 10.30 added its own `getColumns()`method that conflicts with the one in the package. I renamed the method and released a new version.
