### ISSUE TITLE
Support for HasOneThrough?

### ISSUE THREAD

**Issue by mrethical** [staudenmeir/laravel-merged-relations#23]
It seems like HasOneThrough is not supported.

https://github.com/staudenmeir/laravel-merged-relations/blob/9bbf41176014b710c3684e0fedf94cc31a4e2d97/src/Schema/Builders/CreatesMergeViews.php#L96-L115

I tried changing 
https://github.com/staudenmeir/laravel-merged-relations/blob/9bbf41176014b710c3684e0fedf94cc31a4e2d97/src/Schema/Builders/CreatesMergeViews.php#L106

to `if ($relation instanceof HasOneOrManyThrough) {` since both `HasOneTrough` and `HasManyThrough` extends from `HasOneOrManyThrough` and uses the same `getQualifiedFirstKeyName()` and it seems to work.

Is there maybe a reason to not support HasOneThrough relationship?

**Comment by staudenmeir** [comment]
Hi @mrethical,
Thanks for reporting this. The issue is caused by a breaking change in Laravel 11.15 that changed the structure `Has*Through` relations.

I released a new version with a fix.
