### ISSUE TITLE
Error: Class name must be a valid object or a string

### ISSUE THREAD

**Issue by ChrisHardie** [staudenmeir/laravel-merged-relations#3]
I was so happy to find this package today! Thank you for creating it!!

It is mostly working fine for me, but I noticed that when I add a `->select('column')` query modifier to the view query, I get some warnings and errors:

```
<warning>PHP Warning:  Undefined property: stdClass::$laravel_model in vendor/staudenmeir/laravel-merged-relations/src/Eloquent/Builder.php on line 23</warning>
<warning>PHP Warning:  Undefined property: stdClass::$laravel_placeholders in vendor/staudenmeir/laravel-merged-relations/src/Eloquent/Builder.php on line 27</warning>
PHP Error:  Class name must be a valid object or a string in vendor/staudenmeir/laravel-merged-relations/src/Eloquent/Builder.php on line 35
```

Here's the query I'm running:

`$source->newsItems()->select('external_id')->get();`

and the SQL it is generating:

```
select `external_id` from `source_all_newsitems` where `source_all_newsitems`.`laravel_foreign_key` = ? and `source_all_newsitems`.`laravel_foreign_key` is not null"
```

Here's the Source model setup:

```
    public function feedNewsItems()
    {
        return $this->hasManyThrough(NewsItem::class, Feed::class);
    }

    public function directNewsItems()
    {
        return $this->hasMany(NewsItem::class);
    }

    public function newsItems()
    {
        return $this->mergedRelationWithModel(NewsItem::class, 'source_all_newsitems');
    }
```

and the migration:

```
        Schema::createMergeView('source_all_newsitems', [
            (new \App\Models\Source())->feedNewsItems(),
            (new \App\Models\Source())->directNewsItems()
        ]);
```

Note that if I run the query without the `select()` modifier, it works fine. I see the limitation disclaimer about not being able to specify columns in the view creation, but it looks like it should be possible to specify columns in the query of the view, unless I'm missing something.

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by staudenmeir** [comment]
I'll release a new version that makes sure the package's internal columns are always selected.

As a temporary workaround, you need to select them manually:

```php
$source->newsItems()->select('external_id', 'laravel_model', 'laravel_placeholders', 'laravel_with')->get();
```

**Comment by staudenmeir** [comment]
I released a new version for this.
