### ISSUE TITLE
"Base table or view already exists" when running test suite

### ISSUE THREAD

**Issue by ChrisHardie** [staudenmeir/laravel-merged-relations#4]
I'm getting a phpunit test suite set up for a project where I'm using this package, and immediately started encountering "Base table or view already exists" errors for the created view on n>=2 runs of the tests. My best guess is that something about the existence of a view is not expected in the way Laravel handles creating and cleaning up the test database structure. But it's also possible/likely I've configured something incorrectly.

Do you have any guidance on how to address this? For now I'm adding a `Schema::dropViewIfExists()` call to the migration's `up()` method as a workaround. Thank you.

**Comment by staudenmeir** [comment]
Try adding `protected $dropViews = true;` to your test class(es).

**Comment by ChrisHardie** [comment]
That worked, thank you. I opened #5 in case you'd like a related documentation update.
