### ISSUE TITLE
[MergedRelationWithModel] - Merge 3 relationships is not working

### ISSUE THREAD

**Issue by mfmarques** [staudenmeir/laravel-merged-relations#6]
Hello, i can't make the mergedRelationWithModel work with my structure. Can you take a look of what i'm doing wrong?

`Schema::createOrReplaceMergeView('participants', [(new Blog)->user(), (new Blog)->creator(), (new Blog)->commenters()]);`

### Results in:

```
CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `username`@`ip` 
    SQL SECURITY DEFINER
VIEW `database`.`participants` AS
    SELECT 
        `database`.`users`.`username` AS `username`,
        `database`.`users`.`id` AS `laravel_foreign_key`,
        'App\Models\User' AS `laravel_model`,
        '' AS `laravel_placeholders`,
        '' AS `laravel_with`
    FROM
        `database`.`users`
    WHERE
        (`database`.`users`.`deleted_at` IS NULL) 
    UNION ALL SELECT 
        `database`.`users`.`username` AS `username`,
        `database`.`users`.`id` AS `laravel_foreign_key`,
        'App\Models\User' AS `laravel_model`,
        '' AS `laravel_placeholders`,
        '' AS `laravel_with`
    FROM
        `database`.`users`
    WHERE
        (`database`.`users`.`deleted_at` IS NULL) 
    UNION ALL SELECT DISTINCT
        `database`.`users`.`username` AS `username`,
        `database`.`blog_comments`.`blog_id` AS `laravel_foreign_key`,
        'App\Models\User' AS `laravel_model`,
        '' AS `laravel_placeholders`,
        '' AS `laravel_with`
    FROM
        (`database`.`users`
        JOIN `database`.`blog_comments` ON ((`database`.`users`.`id` = `database`.`blog_comments`.`user_id`)))
    WHERE
        (`database`.`users`.`deleted_at` IS NULL)
```

### Blog Model

```
class Blog extends Model
{
    use \Staudenmeir\LaravelMergedRelations\Eloquent\HasMergedRelationships;

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function commenters(): BelongsToMany
    {
        return $this->belongsToMany(User::class, BlogComment::class)->distinct();
    }

    /**
     * Get participants in the blog.
     *
     * @todo: We should get the users who comments + creator + user
     * 
     * @return MergedRelation
     */
    public function participants(): MergedRelation
    {
        return $this->mergedRelationWithModel(User::class, 'participants');
    }
}
```

## Expected result

$blog->participants returns the **user** + **creator** + **commenters** 

## Result

$blog->participants is just returning the commenters

### $blog->participants raw sql query results in:

f3a002e2-5ecb-4205-aefd-cfb2ecc0112e is the primary key for the Blog Model

``select * from `participants` where `participants`.`laravel_foreign_key` = 'f3a002e2-5ecb-4205-aefd-cfb2ecc0112e' and `participants`.`laravel_foreign_key` is not null``

If you need more information, please feel free to tell

Thank you,
Mário

**Comment by staudenmeir** [comment]
Please provide an SQL dump of both tables and some sample rows for me to reproduce the issue.

**Comment by mfmarques** [comment]
@staudenmeir where do you want me to send that? through a link?

**Comment by staudenmeir** [comment]
Can you upload it here?

**Comment by staudenmeir** [comment]
Please also post the whole `Blog` and `User` models.

**Comment by staudenmeir** [comment]
> SQL dump of both tables

And the pivot table, of course.

**Comment by mfmarques** [comment]
The `Blog` was just for this example. The real model is  `Ticket` but the structure is the same as i gave in the `Blog` example.

I have to delete this later. Can you tell me after you download the files so i can delete this?

[dump_models.zip](https://github.com/staudenmeir/laravel-merged-relations/files/7900712/dump_models.zip)

**Comment by staudenmeir** [comment]
Downloaded.

**Comment by mfmarques** [comment]
Thank you.
If you need more information, feel free to say

**Comment by staudenmeir** [comment]
This is an issue with the package, I'm working on a fix.

**Comment by mfmarques** [comment]
Ok, thank you for the feedback.

**Comment by staudenmeir** [comment]
I released a new version that fixes this issue.

**Comment by mfmarques** [comment]
@staudenmeir I've tested and it's working as expected. Thank you
