### ISSUE TITLE
Issue after upgrading with missing method

### ISSUE THREAD

**Issue by JeffreyDavidson** [staudenmeir/laravel-merged-relations#7]
After upgrading this package to the new release and running my test suite which uses sqlite with an in memory database I'm getting an error with it not finding `Call to undefined method Staudenmeir\LaravelMigrationViews\Schema\Builders\SQLiteBuilder::createOrReplaceMergeView()` however if I look inside the vendor folder and find the SQLiteBuilder file I do find the method inside of the CreatesMergeViews trait.

I did not get this error when I ran my tests pior to the upgrading this package and upgrading Laravel to 9.

```
<?php

use App\Models\Group;
use Illuminate\Database\Migrations\Migration;
use Staudenmeir\LaravelMergedRelations\Facades\Schema;

class CreateAllGroupMembersView extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::createOrReplaceMergeView(
            'all_group_members',
            [(new Group)->teachers(), (new Group)->students()]
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropView('all_group_members');
    }
}
```

**Comment by staudenmeir** [comment]
This is an interesting issue, I need to a closer look.

As a temporary workaround, please disable auto-discovery of `staudenmeir/laravel-migration-views` in your `composer.json`:

```json
    "extra": {
        "laravel": {
            "dont-discover": [
                "staudenmeir/laravel-migration-views"
            ]
        }
    },
```

**Comment by JeffreyDavidson** [comment]
Thank you for such a helpful package. I look forward to the solution.

**Comment by staudenmeir** [comment]
I released a new version that fixes this issue.
