### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by nomercy12** [staudenmeir/laravel-merged-relations#8]
Hello,

So am getting this error when I do php artisan migrate, which says:

**Illuminate\Database\QueryException 

SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer at character 499**

Am just doing how the view example shows, here's my code:

```
    use Staudenmeir\LaravelMergedRelations\Facades\Schema;

    public function up()
    {
        Schema::createMergeView(
            'friends_view',
            [( new User())->acceptedFriendsOf(), ( new User())->acceptedFriendsOfMine()]
        );
    }
```

**Comment by staudenmeir** [comment]
Please share the whole error message and the `User` model.

**Comment by staudenmeir** [comment]
Please share the whole error message.

**Comment by nomercy12** [comment]
Migrating: 2022_04_14_164313_create_friends_view_view

   Illuminate\Database\QueryException 

  SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer at character 499
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: create view "friends_view" as (select "users"."id", "users"."name", "users"."email", "users"."email_verified_at", "users"."password", "users"."remember_token", "users"."created_at", "users"."updated_at", "users"."two_factor_secret", "users"."two_factor_recovery_codes", "friends"."friend_id" as laravel_foreign_key, 'App\Models\User' as laravel_model, '' as laravel_placeholders, '' as laravel_with from "users" inner join "friends" on "users"."id" = "friends"."user_id" where "friends"."accepted" = 1) union all (select "users"."id", "users"."name", "users"."email", "users"."email_verified_at", "users"."password", "users"."remember_token", "users"."created_at", "users"."updated_at", "users"."two_factor_secret", "users"."two_factor_recovery_codes", "friends"."user_id" as laravel_foreign_key, 'App\Models\User' as laravel_model, '' as laravel_placeholders, '' as laravel_with from "users" inner join "friends" on "users"."id" = "friends"."friend_id" where "friends"."accepted" = 1))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:716
    712▕         // If an exception occurs when attempting to run a query, we'll format the error
    713▕         // message to include the bindings with SQL, which will make this exception a
    714▕         // lot more helpful to the developer instead of just the database's errors.
    715▕         catch (Exception $e) {
  ➜ 716▕             throw new QueryException(
    717▕                 $query, $this->prepareBindings($bindings), $e
    718▕             );
    719▕         }
    720▕     }

      +8 vendor frames 
  9   database/migrations/2022_04_14_164313_create_friends_view_view.php:19
      Illuminate\Support\Facades\Facade::__callStatic("createMergeView")

      +23 vendor frames 
  33  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by staudenmeir** [comment]
Sorry, I didn't get notified. I'm working on a fix.

What Laravel version are you using?

**Comment by staudenmeir** [comment]
I released a fix for Laravel 9 in the underlying `staudenmeir/laravel-migration-views`.

**Comment by nomercy12** [comment]
Hello,

Am using the latest version.

**Comment by staudenmeir** [comment]
Run `composer update staudenmeir/laravel-migration-views` to get the fix.

**Comment by nomercy12** [comment]
Solved, thanks!
